# Generated by Django 2.2.7 on 2020-05-08 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diseases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=200)),
                ('plant_name', models.CharField(max_length=200)),
                ('disease_description_en', models.CharField(max_length=10000)),
                ('treatment_en', models.CharField(default='', max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='FarmerQueries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.BigIntegerField()),
                ('location', models.CharField(max_length=200)),
                ('query', models.CharField(max_length=10000)),
                ('answer', models.CharField(default='', max_length=10000)),
                ('isQueryAnswered', models.BooleanField(default=False)),
                ('query_date', models.DateTimeField(auto_now=True)),
                ('isQueryViewed', models.BooleanField(default=False)),
            ],
        ),
    ]
