# Generated by Django 2.2.7 on 2020-07-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krushiveda', '0002_diseasetrackrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseasetrackrecord',
            name='dateTime',
            field=models.DateTimeField(),
        ),
    ]
